version: "3"
services:
  mongodb:
    image: mongo:4.0.4
    container_name: mongodb-grpc
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
   